# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inferencia.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'inferencia.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10inferencia.proto\x12\ninferencia\"\x1d\n\x0cPedidoPrever\x12\r\n\x05texto\x18\x01 \x01(\t\"F\n\x0eRespostaPrever\x12\r\n\x05texto\x18\x01 \x01(\t\x12\x12\n\nsentimento\x18\x02 \x01(\t\x12\x11\n\tconfianca\x18\x03 \x01(\x01\"\x1c\n\nPedidoLote\x12\x0e\n\x06textos\x18\x01 \x03(\t\">\n\x0cRespostaLote\x12.\n\nresultados\x18\x01 \x03(\x0b\x32\x1a.inferencia.RespostaPrever2\x8c\x01\n\nInferencia\x12>\n\x06Prever\x12\x18.inferencia.PedidoPrever\x1a\x1a.inferencia.RespostaPrever\x12>\n\nPreverLote\x12\x16.inferencia.PedidoLote\x1a\x18.inferencia.RespostaLoteb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inferencia_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PEDIDOPREVER']._serialized_start=32
  _globals['_PEDIDOPREVER']._serialized_end=61
  _globals['_RESPOSTAPREVER']._serialized_start=63
  _globals['_RESPOSTAPREVER']._serialized_end=133
  _globals['_PEDIDOLOTE']._serialized_start=135
  _globals['_PEDIDOLOTE']._serialized_end=163
  _globals['_RESPOSTALOTE']._serialized_start=165
  _globals['_RESPOSTALOTE']._serialized_end=227
  _globals['_INFERENCIA']._serialized_start=230
  _globals['_INFERENCIA']._serialized_end=370
# @@protoc_insertion_point(module_scope)
