# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import inferencia_pb2 as inferencia__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in inferencia_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InferenciaStub:
    """Contrato do servico - Aula 4.
    Gere os stubs com:
    python -m grpc_tools.protoc -I proto --python_out=. \
    --grpc_python_out=. proto/inferencia.proto

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Prever = channel.unary_unary(
                '/inferencia.Inferencia/Prever',
                request_serializer=inferencia__pb2.PedidoPrever.SerializeToString,
                response_deserializer=inferencia__pb2.RespostaPrever.FromString,
                _registered_method=True)
        self.PreverLote = channel.unary_unary(
                '/inferencia.Inferencia/PreverLote',
                request_serializer=inferencia__pb2.PedidoLote.SerializeToString,
                response_deserializer=inferencia__pb2.RespostaLote.FromString,
                _registered_method=True)


class InferenciaServicer:
    """Contrato do servico - Aula 4.
    Gere os stubs com:
    python -m grpc_tools.protoc -I proto --python_out=. \
    --grpc_python_out=. proto/inferencia.proto

    """

    def Prever(self, request, context):
        """Ja implementado no exemplo.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PreverLote(self, request, context):
        """TAREFA 4: implemente este metodo no servidor gRPC.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InferenciaServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Prever': grpc.unary_unary_rpc_method_handler(
                    servicer.Prever,
                    request_deserializer=inferencia__pb2.PedidoPrever.FromString,
                    response_serializer=inferencia__pb2.RespostaPrever.SerializeToString,
            ),
            'PreverLote': grpc.unary_unary_rpc_method_handler(
                    servicer.PreverLote,
                    request_deserializer=inferencia__pb2.PedidoLote.FromString,
                    response_serializer=inferencia__pb2.RespostaLote.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'inferencia.Inferencia', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('inferencia.Inferencia', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Inferencia:
    """Contrato do servico - Aula 4.
    Gere os stubs com:
    python -m grpc_tools.protoc -I proto --python_out=. \
    --grpc_python_out=. proto/inferencia.proto

    """

    @staticmethod
    def Prever(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inferencia.Inferencia/Prever',
            inferencia__pb2.PedidoPrever.SerializeToString,
            inferencia__pb2.RespostaPrever.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PreverLote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inferencia.Inferencia/PreverLote',
            inferencia__pb2.PedidoLote.SerializeToString,
            inferencia__pb2.RespostaLote.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
